### ISSUE TITLE
[45] Current language

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#314]
As per a user of the eLibrary I'm not able to see the current language in the right corner combo box on the main form. The current language should be selected as default. In case of an below example, the 'en' should be selected instead of the 'pl'.

![image](https://user-images.githubusercontent.com/26207880/130343882-1e3d2419-442c-4bed-8eb6-2c878568f710.png)

**Comment by AKepska** [comment]
I can't reproduce the bug, but I have found new one.  When I'm logged as client, I can't change application's language.
