### ISSUE TITLE
[10] Prolongation wrong error message

### ISSUE THREAD

**Issue by AKepska** [JaRutkowski/eLibrary#355]
After login, switched to load service and clicking  prolonge button, "PLN" is missing in the message.
![image](https://user-images.githubusercontent.com/97629313/207687742-e67cacf1-c552-4408-acaf-d68e561c8607.png)
 Once Return button is clicked, additional {0} appears in the message and the rest is ok.
![image](https://user-images.githubusercontent.com/97629313/207688259-229d636e-9767-46d6-b62c-4c562d77056e.png)
This bug is the result of [20] Prolongation #317 implementation.

**Comment by Jakuberbetowski** [comment]
I think the most important thing is checking a messeges.properties and format those messages. Probably return button doesn't have the support for the new added format of the message.

**Comment by JPerzanowski** [comment]
OK, I will do it.
